load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "testutil",
    srcs = ["testutil.go"],
    importpath = "github.com/ocean2811/tidbeaff0fbc576a/pkg/ddl/ingest/testutil",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ddl/ingest",
        "//pkg/kv",
        "//pkg/sessionctx",
        "//pkg/testkit",
    ],
)
