load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cli",
    srcs = ["versions.go"],
    importpath = "github.com/ocean2811/tidbeaff0fbc576a/dumpling/cli",
    visibility = ["//visibility:public"],
    deps = [
        "//dumpling/log",
        "@org_uber_go_zap//:zap",
    ],
)
